### ISSUE TITLE
Unable to import shapes

### ISSUE THREAD

**Issue by samporapeli** [brycedorn/react-legos#36]
I ran into an import error while trying to use this library:
`export 'shapes' (imported as 'shapes') was not found in 'react-legos' (possible exports: __esModule, colors, default, sizes)`
I used create-react-app to initialize a new React application, after which I modified the default `App.js` to include one brick, just as shown in the README:
```jsx
import React from 'react'
import logo from './logo.svg'
import './App.css'
import Brick, { shapes } from 'react-legos'

const App = () => {
  return (
    <div className="App">
      <h1>Example brick</h1>
      <Brick shape={shapes['twoByFour']} />
    </div>
  )
}

export default App
```

I took a quick look at the source code history and found that the `shapes` export seems to be deleted in [this commit](https://github.com/brycedorn/react-legos/commit/7499590dba7694b69a7aa4e488ce286a6ea80a6d#diff-92bbac9a308cd5fcf9db165841f2d90ce981baddcb2b1e26cfff170929af3bd1L10).

Am I doing something wrong, or is the README outdated, or was the removal of `shapes` export accidental? In any case, I'd appreciate help as this library looks very promising, possibly something I could use in a project ☺️

**Comment by brycedorn** [comment]
Hey @samporapeli! Sorry for the late reply - you are indeed correct I mistakenly removed the `shapes` export making the readme out of date 😞. I can re-add it, but in the meantime you can still reference `shapes` exports directly, like so:

```jsx
import React from "react";
import Brick from "react-legos";
import { twoByFour } from "react-legos/dist/shapes";

const App = () => {
  return (
    <div className="App">
      <h1>Example brick</h1>
      <Brick shape={twoByFour} />
    </div>
  );
};

export default App;
```
