### ISSUE TITLE
Bricks overlap

### ISSUE THREAD

**Issue by hvitis** [brycedorn/react-legos#9]
Hello!

When adding next bricks they seem to overlap if no style is provided
```react
        <div > <Brick shape={[[1, 0, 1, 1, 1, 1, 1, 1]]} /></div>
        <div > <Brick shape={[[1, 0, 1, 1, 1, 1, 1, 0]]} /></div>
        <div > <Brick shape={[[1, 0, 1, 1, 0, 1, 1, 1]]} /></div>
        <div style={{ marginTop: 100 }}> <Brick shape={[[1, 1, 1, 1, 1]]} /></div>

```

![image](https://user-images.githubusercontent.com/17104239/73581045-3db90c80-4488-11ea-935f-d8b739bb62f2.png)

Any ideas?

Great library, thanks a lot!

**Comment by brycedorn** [comment]
hi @hvitis, sorry for getting to this late!

the components aren't aware of each other, unfortunately. I would like to implement this but haven't gotten around to it. for now, you'll need to manually apply a `top` & `left` offset to position them on the page.

**Comment by hvitis** [comment]
Thank you!
